export const ADD_BOOK_TO_BASKET = "ADD_BOOK_TO_BASKET";
export const REMOVE_BOOK_FROM_BASKET = "REMOVE_BOOK_FROM_BASKET";
export const ADD_BOOK = "ADD_BOOK";
export const REMOVE_BOOK = "REMOVE_BOOK";

export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_AUTHOR = "CHANGE_AUTHOR";
export const CHANGE_PRICE = "CHANGE_PRICE";

export const CHANGE_SEARCH = "CHANGE_SEARCH";
